### ISSUE TITLE
Possible to consolidate license files?

### ISSUE THREAD

**Issue by tweed1e** [medewitt/tidyqwi#21]
RE: JOSS review https://github.com/openjournals/joss-reviews/issues/1462, is there a way to combine the LICENSE and LICENSE.md files into one plain-text (.md or other) license file? 

I'm not sure what the CRAN license file requirements are, but LICENSE doesn't say what type of license it is, and LICENSE.md says MIT, so one consistent file would avoid the confusion 🙏.

**Comment by medewitt** [comment]
@tweed1e good question. I will check that out and see what I can do.

**Comment by medewitt** [comment]
@tweed1e per CRAN [guidelines ](https://cran.r-project.org/web/packages/policies.html)it looks like I can remove the LICENSE.md file as long as I have the license text in the DESCRIPTION file [(License: MIT + License)](https://www.r-project.org/Licenses/MIT) and have the LICENSE (plain text with copyright year)(more for printing the license text on github). I'll go ahead and remove the markdown license version.

**Comment by medewitt** [comment]
Resolved with #23
